### ISSUE TITLE
outputfile

### ISSUE THREAD

**Issue by SetiZ** [misaelnieto/web_to_pdf_action#2]
This question may be stupid but where is the outputfile? I can't find it in my repo. Did I miss something?

**Comment by EndermanAPM** [comment]
Hey @SetiZ , perhaps you could use [this action](https://github.com/marketplace/actions/add-commit) to commit the pdf to your repo.

**Comment by SetiZ** [comment]
nice ! great actions!!

**Comment by SetiZ** [comment]
hey thanks! it works really well!!
closing the issue
